name: Steps validate on PR

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  quality_bdd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Checkout do Código para Mock
        uses: actions/checkout@v2
        with:
          repository: santos-gabriel/fiap-mock
          ref: main
          path: caminho/para/aplicacao-de-mock

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Iniciar aplicação de mock
        run: |
          export MOCK_APP_URL=http://localhost:4000
          npm install
          npm run start &
        env:
          MOCK_APP_URL: http://localhost:4000
        working-directory: caminho/para/aplicacao-de-mock

      - name: Aguardar Inicialização aplicação de mock
        run: sleep 30s

      - name: Construir com Maven
        run: mvn clean install -DskipTests

      - name: Executar testes
        run: mvn spring-boot:run "-Dspring-boot.run.profiles=dev" &

      - name: Aguardar Inicialização
        run: sleep 30s

      - name: Executar BDD
        run: mvn test -Psystem-test

      - name: Encerrar Aplicação
        run: pkill -f "spring-boot:run"

  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Configurar JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'adopt'
  #         java-version: '17'
  #         java-package: 'jdk'
  #         architecture: 'x64'

  #     - name: Executar testes
  #       run: mvn clean install -Pcoverage

  #     - name: Gerar report
  #       run: mvn jacoco:report

  #     - name: Enviar report para o sonar
  #       run: mvn sonar:sonar -Dsonar.organization=pauloloboneto -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{secrets.SONARCLOUD_TOKEN}} -Dsonar.projectKey=PauloLoboNeto_pagamentos -Dsonar.projectName=pagamentos -Dsonar.java.coveragePlugin=jacoco -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
